### ISSUE TITLE
Change Undercurl Style

### ISSUE THREAD

**Issue by MasterMedo** [hexoctal/st-undercurl#2] opened 2021-05-03 11:53 UTC
Is there a way to change the style of the curlies? They are kinda ugly. I'd prefer them to be like elongated w's or v's (vvvvvvvvv).

**EDIT**: I just noticed the squigglies are being drawn manually, I'll take a shot at it this week if I find time!

**Comment by derriche-massinissa** [comment] 2021-05-03 14:03
I'm planning to rewrite the rendering part, I just wanted something working for now, and I'm kind of busy these days. Feel free to implement something yourself, I'll leave this issue open, in case you have questions.

**Comment by NTBBloodbath** [comment] 2021-07-30 00:32
Hey, is there any advance on it? I was playing around with the drawing but can't get it to look beauty :confused:

**Comment by MasterMedo** [comment] 2021-07-30 06:18
I got them working but I didn't like them, a lot of trial and error is needed to get the angle visually pleasing (not to mention line thickness). After spending an hour on this, I figured it's not worth the time. The original squigglies looked better so I ended up reverting to the initial state.

**Comment by MasterMedo** [comment] 2021-07-30 16:21
I'll take another shot at it, I'll post progress as I go.

This code mimics simple underlines:
![image](https://user-images.githubusercontent.com/16375100/127682282-cb96ed75-c6e2-49f5-8cf0-255dad1b3123.png)

You replace everything below `// Draw waves` with:
```c
        XPoint *points = xmalloc(sizeof(XPoint) * 2);
        points[0] = (XPoint) {
          .x = wx,
          .y = wy + wh/2
        };
        points[1] = (XPoint) {
          .x = ww * charlen,
          .y = 0
        };
        XDrawLines(xw.dpy, XftDrawDrawable(xw.draw), ugc, points, 2, CoordModePrevious);

        free(points);
```

**Comment by MasterMedo** [comment] 2021-07-30 16:35
Here is the result if the line changes angle once at each character.
![image](https://user-images.githubusercontent.com/16375100/127683955-5cbd0ebc-d470-4d48-b307-8d32cd60d5d9.png)

You replace everything below `// Draw waves` with:
```c
        int npoints = charlen + 1;
        XPoint *points = xmalloc(sizeof(XPoint) * npoints);
        points[0] = (XPoint) {
          .x = wx,
          .y = wy + wh
        };
        for (int i = 1; i < npoints; i++) {
          points[i] = (XPoint) {
            .x = ww,
            .y = i % 2 ? -wh/2 : wh/2,
          };
        }
        XDrawLines(xw.dpy, XftDrawDrawable(xw.draw), ugc, points, npoints, CoordModePrevious);

        free(points);
```

**Comment by MasterMedo** [comment] 2021-07-30 16:38
And here's when we have two angle changes per character:
![image](https://user-images.githubusercontent.com/16375100/127684405-75482cc2-c999-4b11-9f7f-c823c8cb22cf.png)

You replace everything below `// Draw waves` with:
```c
        int npoints = charlen * 2 + 1;
        XPoint *points = xmalloc(sizeof(XPoint) * npoints);
        points[0] = (XPoint) {
          .x = wx,
          .y = wy + wh
        };
        for (int i = 1; i < npoints; i++) {
          points[i] = (XPoint) {
            .x = ww/2,
            .y = i % 2 ? -wh/2 : wh/2,
          };
        }
        XDrawLines(xw.dpy, XftDrawDrawable(xw.draw), ugc, points, npoints, CoordModePrevious);

        free(points);
```

**Comment by NTBBloodbath** [comment] 2021-07-30 16:44
wow, looking really nice, thank you so much for sharing this! :heart:

**Comment by MasterMedo** [comment] 2021-07-30 16:49
@hexoctal is there any standard to make lines thicker in x? I tried googling a bit, but didn't find anything. A workaround I came up with is drawing the same lines a pixel below (I don't know if this is good). Also, can you check if I cleaned the memory properly. I think I did, but I got some artifacts once when developing, and I'm not sure if that's my fault.

Also, would you mind accepting this as a PR? A user could choose in the `config.h` which style to use.

**Comment by derriche-massinissa** [comment] 2021-08-17 10:31
Hi! First of all I am so sorry for being so late! Github didn't show me any notifications even though I'm subscribed to this issue, and it's only after I randomly checked my emails that I saw your comments :confused:

For line width, you can modify it using GC components like you would do with cap style and fill. Look higher, where ugc is created. But the problem is that xlib do not have subpixel rendering capabilities, so the width is an integer. 1 is what this is already set to and 2 is way too thick...

Something I found to improve the quality of the underline is the angle used. Here is what the lines look like with a 45°, 1 pixel width at different sizes:
![2021-08-17_10-49-54_359x39_scrot](https://user-images.githubusercontent.com/80908175/129705084-1829dde4-7c84-47a7-aa0a-db557134f560.png)

![2021-08-17_10-50-05_593x77_scrot](https://user-images.githubusercontent.com/80908175/129705118-33070aec-dd33-4182-8411-e81dfd397b85.png)

![2021-08-17_10-50-17_905x100_scrot](https://user-images.githubusercontent.com/80908175/129705139-8a6c72e3-7fe4-4a94-8662-606489875ac2.png)

And yes, as you can see, the line is too thin, but a width of 2 gives this:
![2021-08-17_10-56-18_388x37_scrot](https://user-images.githubusercontent.com/80908175/129705507-7346f26f-fa7d-49e1-9662-9c9bfb85ef63.png)

![2021-08-17_10-56-27_631x69_scrot](https://user-images.githubusercontent.com/80908175/129705521-9689bcc8-319e-463f-81c6-5ec8d1020bff.png)

![2021-08-17_10-56-46_970x125_scrot](https://user-images.githubusercontent.com/80908175/129705529-779a1d54-d1e8-4df1-b662-5aaad6b6f944.png)

Taking for example the curly underline of firefox right in this comment text area, the lines when at 1 pixel width are drawn as follow:
![2021-08-17_11-03-13_680x180_scrot](https://user-images.githubusercontent.com/80908175/129707452-f5f59f0b-d1df-438d-b784-d089d91bc35d.png)

But XLib does it like this:
![2021-08-17_11-03-05_718x159_scrot](https://user-images.githubusercontent.com/80908175/129707492-d9e7111d-ba96-43d4-a563-1e4a3f6e079b.png)

This makes the joints look spiky and lines too thin. A solution to this could be as you said to draw the line twice:
![2021-08-17_11-03-21_720x191_scrot](https://user-images.githubusercontent.com/80908175/129707841-63d37f6a-2280-4579-a5bb-8f3c3cefeea5.png)

So with all this, this is what we could conclude to draw straight lines as curly underlines:
- Keep angle of lines at 45° otherwise the lines look weird depending on the font size
- Adapt the width of the line to the size of the font (A bit tricky as we cannot use floating precision)
- Draw the lines twice to imitate a width of 1.5 for small font sizes with an offset of 1 pixel to the right

I put all this together and got the following results:
![2021-08-17_11-17-46_375x40_scrot](https://user-images.githubusercontent.com/80908175/129708999-44d6a790-2ffa-4ef6-8f82-02461779a0ab.png)
![2021-08-17_11-17-57_560x64_scrot](https://user-images.githubusercontent.com/80908175/129709013-8f7c8b33-4186-49d8-a69e-4fcfa6f11020.png)
![2021-08-17_11-18-54_978x99_scrot](https://user-images.githubusercontent.com/80908175/129709049-1eb83b2c-31a4-4fe3-bda4-762b751359a1.png)

Which I find looks quite good and clean, I'm gonna fix the width of the underline to match its word, and also work on a solution to update a single wave when a redraw is needed, this is a little more delicate as the 45° angle removes the convenience of having 1 wave per character:
![2021-08-17_11-29-38_194x79_scrot](https://user-images.githubusercontent.com/80908175/129710597-9c75c2cd-18d4-4e32-b128-12ec09175827.png)

Anyway tell me what you think about these results. I'll post an update as soon as I fix the length and redraw problem!

**Comment by derriche-massinissa** [comment] 2021-08-17 10:34
Also @MasterMedo what kind of artifact was it? It could be a conflict with another patch

**Comment by MasterMedo** [comment] 2021-08-17 10:42
When I first started the issue I also went for the 45 degree angle and got stuck on this exact thing: connecting two independent waves.

Artifacts I had were xlines drawn from 0,0 to my cursor in neovim. I must've forgotten to comment some line because I haven't seen them since.

**Comment by derriche-massinissa** [comment] 2021-08-17 18:09
So after a while, I implemented everything for this style. Here are some screenshots:
![2021-08-17_18-44-21_1600x900_scrot](https://user-images.githubusercontent.com/80908175/129777020-143c0856-5e25-473a-bf3e-a81a41d1ec67.png)
![2021-08-17_18-44-34_1600x900_scrot](https://user-images.githubusercontent.com/80908175/129777039-5343e5df-db89-4a6e-a2df-ac445fbdcf83.png)
![2021-08-17_18-57-21_1600x900_scrot](https://user-images.githubusercontent.com/80908175/129777049-3e154cd5-3f0a-42e7-953e-189bfc32888a.png)

I fixed the problem of wave connection by using an absolute grid for the underline that do not use the text coordinates but the screen coordinates (Came up with the idea after observing Firefox's underline). It works pretty well.

Tell me what you think of this, and if any of you have remarks or observations like the width, height and sol on...

I have an idea about another style too: Instead of having spiky waves like the above:
```
\/\/\/\/\/\/\
```
It's gonna draw waves with capped joints like so:
```
 _   _   _   _
/ \_/ \_/ \_/
```
I'll try it and see how it goes. I'm also gonna add the option to choose between the 3 different styles in the config file.

**Comment by MasterMedo** [comment] 2021-08-17 20:07
Can you put it in a pull request draft, so I can check it out?

It definitely looks promising. How did you get screen coordinates, I tried using the grid with character coordinates, but that didn't work with unicode.

Pretty cool idea for the third style.

**Comment by derriche-massinissa** [comment] 2021-08-17 20:38
Sure, will do as soon as possible, maybe tomorrow.
I get the coordinates using the variable winx and winy, they are already present in st.

**Comment by derriche-massinissa** [comment] 2021-08-18 14:15
I added a new development branch with the new patch, so check it out.
https://github.com/hexoctal/st-undercurl/tree/develop

It's little rough around the edges for now but enough for testing it. Change the style of the underline in the config.def.h. Don't forget to delete the generated config.h before recompiling.

**Comment by NTBBloodbath** [comment] 2021-08-18 15:14
Hey, I'm trying to test it out but I'm getting errors like this one:

```
x.c: In function ‘xdrawglyphfontspecs’:
x.c:1725:26: error: ‘Glyph_’ doesn't have a member called ‘ucolor’
 1725 |                 if ((base.ucolor[0] >= 0) &&
      |                          ^
```

Should I try with an unpatched version of st? :thinking:

Regards

**Comment by hexoctal** [comment] 2021-08-18 15:22
Oh, forgot to add a file to the patch! I'll fix it right away!

**Comment by derriche-massinissa** [comment] 2021-08-18 15:29
I just checked and the patch works correctly. I noticed that the name of the struct in your comment is "Glyph_" with an underscore, so you might have a patch that's causing troubles... Try it with an unpatched version first. It would be helpful if you could find which patch causes this problem too.

**Comment by MasterMedo** [comment] 2021-08-18 20:07
Works for me! I like the spiky version most, probably going to stick to that one. I like the threshold variable, although I think it would be more clear if you called it width (e.g. `10/threshold`).

**EDIT:** (I went through the code)
yeah, this threshold thing seems unnecessarily complex to me as a user:
`wlw = (win.ch / UNDERCURL_WIDTH_THRESHOLD) + 1`

**Comment by derriche-massinissa** [comment] 2021-08-19 06:17
Threshold is just how often should the underline width increase. By default it is 40 which means that the line width increase by 1 pixel every time the terminal font increases by 40px. I didn't really intend to have it as a config though so I'll move it somewhere else. I made this system to imitate a 0.5 increase in width as Xlib do no have subpixel rendering.

**Comment by MasterMedo** [comment] 2021-08-19 11:22
In neovim, words containing non-latin characters e.g. `čćđšž` curl one character too much:
![image](https://user-images.githubusercontent.com/16375100/130060112-e3974112-f83d-43e8-acf0-9a86c5a2c6a1.png)

I suspect this has nothing to do with your code though. Because in shell (fish) this doesn't happen:
![image](https://user-images.githubusercontent.com/16375100/130060363-0ca91fb7-516d-42ef-ab20-15e05a379a7d.png)

**Comment by derriche-massinissa** [comment] 2021-08-19 15:55
I can't seem to reproduce the issue inside or outside of neovim.
![2021-08-19_16-46-10_144x243_scrot](https://user-images.githubusercontent.com/80908175/130101227-cac28d1e-0026-4937-a248-e25ebdd340d7.png)

Initially I suspected that the end of line special character was the culprit, but that wasn't the case too.
![2021-08-19_16-51-29_169x233_scrot](https://user-images.githubusercontent.com/80908175/130101248-acd71392-30ba-45fd-9129-385eb20042d3.png)

So I believe that it is caused by a plugin. I get dimensions from st itself, so whatever is causing this is probably modifying a core part of st. :man_shrugging:

**Comment by derriche-massinissa** [comment] 2021-08-22 09:00
I updated the master branch with the new patch. If everything is good, we'll close this issue.

**Closed as completed** 2021-08-22 09:01 UTC
Labels: enhancement
